"""initial migration

Revision ID: d9e22c1a258b
Revises: 
Create Date: 2026-06-10 15:12:38.956621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e22c1a258b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_wardrobe',
    sa.Column('id_default', sa.Integer(), nullable=False),
    sa.Column('nama_pakaian', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('warna_grup', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_default')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('personal_wardrobe',
    sa.Column('id_personal', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_pakaian', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('warna_grup', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_personal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_wardrobe')
    op.drop_table('users')
    op.drop_table('default_wardrobe')
    # ### end Alembic commands ###
